language: python
python:
  - "2.7"

install:
  - "pip install -r requirements.txt"

script: 
  - nosetests --with-coverage --cover-package=model --cover-package=data
  - coverage run --source=model --source=data amity.py test
after-success:
  - coveralls